### PR TITLE
assist app - made email thingy easier

### PR DESCRIPTION
**Pull request by Okmeque1**

### CODE REVIEW

**Comment by Okmeque1** [comment]
Imma release the rest of this on [okmeque1/software](https://github.com/Okmeque1/Software) as G-AIO, you can still have the code if you want.

**Comment by GamerSoft24** [comment]
@Okmeque1 i will be reviewing this piece of code, this is the [.patch file](https://github.com/GamerSoft24/Software/pull/62.patch) for differences and patches overview.

**Comment by GamerSoft24** [comment]
@Okmeque1 i will reopen the pull request now and evaluate the circumstances for the update's necessity and requirements.

**Review by GamerSoft24 — APPROVED** [review]
approved but i will change some stuff

**Comment by GamerSoft24** [comment]
why is this open again

**Pull request merged**
